vtex-apps/search

CHANGELOG.md, docs/Banner.md, docs/DidYouMean.md, docs/README.md, docs/Suggestions.md, graphql/schema.graphql, manifest.json, messages/context.json, messages/en.json, messages/es.json, messages/pt.json, react/Banner.js, react/DidYouMean.js, react/SearchContext.js, react/Suggestions.js, react/components/Banner/index.tsx, react/components/DidYouMean/index.tsx, react/components/Suggestions/index.tsx, react/components/Suggestions/styles.css, react/graphql/searchResult.gql, react/models/vtex-search-result.js, store/interfaces.json
[workspace](https://didyoumean--biggy.myvtex.com/search?_query=almofadu)
=> Add DidYouMean, Banner and Suggestions

CHANGELOG.md, docs/Banner.md, docs/DidYouMean.md, docs/README.md, docs/Suggestions.md, store/interfaces.json
eu mantive os componentes`search-result-layout.desktop.enhanced`  e o `search-result-layout.mobile.enhanced"` porque existem clientes que estão usando. Criei uma issue para remover ele na proxima Major.
=> remove allowed

CHANGELOG.md, react/components/SearchQuery.js
Example workspace: https://christian--exitocol.myvtex.com/search?_query=dasdasdasdadad
=> Use ft in map to enable not-found-layout

CHANGELOG.md, manifest.json, node/commons/compatibility-layer.ts, node/package.json, react/components/SearchQuery.js, react/package.json
In this pr:
- verification if the product sku has any price.
=> check if the sku has any price

CHANGELOG.md, node/commons/compatibility-layer.ts, node/typings/elasticProduct.ts, node/typings/vtexProduct.ts
This PR depends on another bug fix. Please, don't merge this without my concern.
=> send all images from api and filter skus by stock

CHANGELOG.md, docs/README.md
=> Add Google Analytics config docs

CHANGELOG.md, docs/README.md
=> Improve docs for order options

CHANGELOG.md, react/components/Autocomplete/components/TileList/TileList.tsx
Issue: https://github.com/vtex-apps/search/issues/63
[workspace](https://hiago--samsungbr.myvtex.com/)
=> use Link instead of a

CHANGELOG.md, docs/Autocomplete.md, react/components/Autocomplete/index.tsx
As the title says.
[Workspace with warn](https://thalyta--storecomponents.myvtex.com/)
=> Use __unstableProductOriginVtex

CHANGELOG.md, node/commons/compatibility-layer.ts
Fix duplicated images when the store has the split property enabled
[workspace](https://searchv1--alssports.myvtex.com/)
=> change cacheId when there is split

CHANGELOG.md, node/commons/compatibility-layer.ts
Add cacheId to the `convertBiggyProduct`
[Workspace](https://searchv1--alssports.myvtex.com/shirt?_q=shirt&map=ft)
✔️ | Type of Change
---|---
✔️| Bug fix 
_ | New feature 
_ | Breaking change 
_ | Technical improvements
=> add cacheId

CHANGELOG.md, react/components/Autocomplete/components/CustomListItem/CustomListItem.tsx
Adding ListPrice to CustomListItem in mobile autocomplete biggy search
[Workspace](https://biggysearch--aurelia.myvtex.com/)
=> Added ListPrice in CustomListItem

CHANGELOG.md, manifest.json, react/components/Autocomplete/index.tsx
When using the autocomplete, the following error was displayed on the console:
Test:
- [Workspace](https://hiago--quebramar.myvtex.com/homem/colecao/calcas?__bindingAddress=quebramar.com/pt)
- search for something and wait for the autocomplete to appear
=> Fix error on dispatch

CHANGELOG.md, react/components/Banner/index.tsx
Once this one is approved I will do the same thing to the `v1.x` version!
=> fix error when serachquery is missing

CHANGELOG.md, react/components/Autocomplete/components/TileList/styles.css
Before
- Adding tileListList componente **classname**.
=> Adding tileListList component classname

CHANGELOG.md, manifest.json, react/components/Autocomplete/components/CustomListItem/CustomListItem.tsx, react/components/Autocomplete/components/ItemList/ItemList.tsx, react/components/Autocomplete/components/TileList/TileList.tsx, react/components/Autocomplete/index.tsx, react/utils/biggy-client.ts, react/utils/pixel.ts, react/utils/withUsePixel.tsx
Send pixel messages on autocomplete interaction
```
"product_click",
"search_suggestion_click",
"top_search_click",
"history_click",
"search",
"empty_search",
"see_all_click",
```
[workspace](https://hiago--eriksbikeshop.myvtex.com/bike?map=ft)
=> add pixel events

CHANGELOG.md, docs/README.md, react/components/Autocomplete/components/ItemList/Attribute.tsx, react/components/Autocomplete/components/ItemList/ItemList.tsx, react/components/Autocomplete/components/ItemList/styles.css, react/package.json, react/yarn.lock
This solves the style gap there was css class in the items
Now some elements have added css classes 
[Workspace](https://mcdon28--devmcdbrdeliveryio.myvtex.com/)
Very happy to be able to contribute with vtex
=> New Css Classes

CHANGELOG.md, react/components/Autocomplete/components/TileList/TileList.tsx, react/components/Autocomplete/components/TileList/styles.css
Add `tileListFooter` CSS handler to the `<footer>`.
=> add tleListFooter handler

CHANGELOG.md, node/clients/search-resolver.ts, node/package.json, node/yarn.lock, react/package.json, react/yarn.lock
It's the same thing from https://github.com/vtex-apps/search/pull/133, but for the 0.x
[workspace](https://hiago--exitocol.myvtex.com/)
=> add x-vtex-provider

.github/workflows/pull-request.yml
related to https://github.com/vtex-apps/search-resolver/pull/228
=> Fix workflow to delete workspace

CHANGELOG.md, react/components/Autocomplete/index.tsx, react/utils/dom-utils.ts
Related to https://github.com/vtex-apps/store/pull/542
=> Safely decoding the URI in case there is any breaking character such as "%"

CHANGELOG.md, messages/fr.json, messages/th.json
Add French and Thai translations, requested in [LOC-8160](https://vtex-dev.atlassian.net/browse/LOC-8160) and [LOC-8169](https://vtex-dev.atlassian.net/browse/LOC-8169)
=> Add French and Thai translations

CHANGELOG.md, messages/ro.json
Add Romanian translation. It replaces the https://github.com/vtex-apps/search/pull/169 PR.
=> add romanian

CHANGELOG.md, messages/id.json
Add Indonesian translation. Tracked by task [LOC-9012](https://vtex-dev.atlassian.net/browse/LOC-9012).
=> Add Indonesian translation

messages/it.json
The current app does not offer italian translation, and our customer Canali in Italy has requested it.
Therefore, we have added it to the code.
You can test it here: https://fixprojecttasks--canali.myvtex.com/?__bindingAddress=it.canali.com/
=> Add italian translation

CHANGELOG.md, docs/Autocomplete.md, docs/Banner.md, docs/DidYouMean.md, docs/README.md, docs/Suggestions.md
[EDU-11500](https://vtex-dev.atlassian.net/browse/EDU-11500)
[EDU-11500]: https://vtex-dev.atlassian.net/browse/EDU-11500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: add before you begin section and edit markdown

docs/README.md
[EDU-4082](https://vtex-dev.atlassian.net/browse/EDU-4082)
[EDU-4082]: https://vtex-dev.atlassian.net/browse/EDU-4082?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: update README.md with catalog integration info
